### testing api call

### User
### Get user
GET http://localhost:8000/api/v1/usersdd
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZG9lLmNvbSIsImlhdCI6MTc1MjczNTUyOSwiZXhwIjoxNzUyODIxOTI5fQ.Cx6YdAb6wtMj9Rf8J6odeZ5hxmb9ygdrl-_KAfUPYJ4


### Post new user
POST http://localhost:8000/api/v1/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john@doe.com",
  "password": "Password@123"
}

### Login user
POST http://localhost:8000/api/v1/users/login
Content-Type: application/json

{
  "email": "john@doe.com",
  "password": "Password@123"
}


### Transactions: all private routers

### Post new transaction
POST http://localhost:8000/api/v1/transactions
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZG9lLmNvbSIsImlhdCI6MTc1Mjc0MDc3NiwiZXhwIjoxNzUyODI3MTc2fQ.WNwB9dKlR0q25PwonLnoNwlLCKMe--M8d81NRSqRImI

{
  "type": "expenses",
  "title": "Grocery",
  "amount": 400,
  "tDate": "2023-02-23"
}

### Get all transactions for the specific user
GET http://localhost:8000/api/v1/transactions
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZG9lLmNvbSIsImlhdCI6MTc1MjczNTUyOSwiZXhwIjoxNzUyODIxOTI5fQ.Cx6YdAb6wtMj9Rf8J6odeZ5hxmb9ygdrl-_KAfUPYJ4

### Delete transaction(s) for a specific user
DELETE http://localhost:8000/api/v1/transactions
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZG9lLmNvbSIsImlhdCI6MTc1MjczNTUyOSwiZXhwIjoxNzUyODIxOTI5fQ.Cx6YdAb6wtMj9Rf8J6odeZ5hxmb9ygdrl-_KAfUPYJ4

["6878d21bfcc6a1b2aa509023", "6878d1fefcc6a1b2aa509018"]
